//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Ведомости
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ведомости()
        {
            this.Итог_дисциплин = new HashSet<Итог_дисциплин>();
        }
    
        public int Id_ведомости { get; set; }
        public string Название { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public int Группа { get; set; }
        public int Нагрузка { get; set; }
        public Nullable<double> Процент_сдавщих { get; set; }
        public Nullable<double> Процент_несдавщих { get; set; }
        public Nullable<double> Процент_троешников { get; set; }
        public Nullable<double> Процент_отличников { get; set; }
        public string Примечание { get; set; }
        public string Файл { get; set; }
        public string Статус { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual ДисцпилинаПреподователь ДисцпилинаПреподователь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Итог_дисциплин> Итог_дисциплин { get; set; }

        public string GetVedomost
        {
            get
            {
                if (Файл != null)
                    return Directory.GetCurrentDirectory() + @"\Vedomost\" + Файл.Trim();
                return null;
            }
        }
    }
}
