//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДисцпилинаПреподователь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ДисцпилинаПреподователь()
        {
            this.Ведомости = new HashSet<Ведомости>();
        }
    
        public int Id_нагрузки { get; set; }
        public int Id_плана { get; set; }
        public Nullable<int> Id_сотрудника { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомости> Ведомости { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Учебный_план Учебный_план { get; set; }
    }
}
