//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Итог_дисциплин
    {
        public int Id_студента { get; set; }
        public int Id_дисциплины { get; set; }
        public Nullable<double> Общий_балл { get; set; }
        public Nullable<int> Оценка { get; set; }
    
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
