//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Итог_дисциплин
    {
        public int Id_итог { get; set; }
        public int Id_плана { get; set; }
        public int Id_студента { get; set; }
        public Nullable<double> Общий_балл { get; set; }
        public Nullable<int> Оценка { get; set; }
        public Nullable<System.DateTime> Дата_зачета { get; set; }
        public Nullable<int> Id_ведомость { get; set; }
    
        public virtual Ведомости Ведомости { get; set; }
        public virtual Студенты Студенты { get; set; }
        public virtual Учебный_план Учебный_план { get; set; }
    }
}
