//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пропуски
    {
        public int Id_пропуска { get; set; }
        public int Id_студента { get; set; }
        public int Id_плана { get; set; }
        public int Id_типа_пропуска { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время { get; set; }
        public string Скан { get; set; }
    
        public virtual Студенты Студенты { get; set; }
        public virtual Тип_пропусков Тип_пропусков { get; set; }
        public virtual Учебный_план Учебный_план { get; set; }
    }
}
