//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Расписание
    {
        public int Id_расписания { get; set; }
        public string Файл { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Дата_завершения { get; set; }
        public string Категория { get; set; }

        public string GetRaspisanie
        {
            get
            {
                if (Файл != null)
                return Directory.GetCurrentDirectory() + @"\Fails\" + Файл.Trim();
                return null;
            }
        }
    }
}
