//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ККТД.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учебный_план
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Учебный_план()
        {
            this.ДисцпилинаПреподователь = new HashSet<ДисцпилинаПреподователь>();
            this.Итог_дисциплин = new HashSet<Итог_дисциплин>();
            this.Пропуски = new HashSet<Пропуски>();
            this.Успеваемость = new HashSet<Успеваемость>();
        }
    
        public int Id_плана { get; set; }
        public int Id_дисциплины { get; set; }
        public Nullable<int> Курс { get; set; }
        public Nullable<int> Семестр { get; set; }
        public Nullable<int> Количество_часов { get; set; }
        public Nullable<int> Id_вид_зачета { get; set; }
    
        public virtual Вид_зачета Вид_зачета { get; set; }
        public virtual Дисциплины Дисциплины { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДисцпилинаПреподователь> ДисцпилинаПреподователь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Итог_дисциплин> Итог_дисциплин { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пропуски> Пропуски { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Успеваемость> Успеваемость { get; set; }
    }
}
